# Site settings
title: DevBlackOps
description: Thoughts about DevOps and automation from a Windows guy
#url: 'https://devblackops.github.io/'
#baseurl: 'https://devblackops.github.io/'
url: 'https://devblackops.io/'
baseurl: 'https://devblackops.io/'
#url: ''
#baseurl: '/'
enforce_ssl: devblackops.io
google_analytics: 'UA-54364644-2'
disqus_shortname: devblackops

#nav_background: images/pdx_lg.jpg

author:
  name: 'Brandon olin'
  email: brandon@devblackops.io
  twitter_username: devblackops
  #facebook_username: joshgerdes
  github_username:  devblackops
  linkedin_username:  brandonolin

pages_list:
  Home: '/'
  About: '/about'
  Archives: '/archives'
  Projects: '/projects'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  -
    scope:
      path: ''
      type: 'projects'
    values:
      layout: 'project-summary'

collections:
  projects:
    output: true


# Build settings
destination: _site
paginate: 5
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-gist
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
