# Site settings
title: DevBlackOps
description: Thoughts about DevOps and automation from a Windows guy
url: 'https://devblackops.io/'
baseurl: 'https://devblackops.io'
#url: ''
#baseurl: ''
enforce_ssl: devblackops.io
google_analytics: 'UA-54364644-2'
disqus_shortname: devblackops

#nav_background: images/pdx_lg.jpg

author:
  name: 'Brandon olin'
  email: brandon@devblackops.io
  twitter_username: devblackops
  #facebook_username: nobody
  github_username:  devblackops
  linkedin_username:  brandonolin
  youtube_channel: UCPAA3UOoho0ZDsXI8BWYrYw

pages_list:
  Home: '/'
  About: '/about/'
  Archives: '/archives/'
  Podcasts: '/podcasts/'
  Projects: '/projects/'
  Training: '/training/'
  Videos: 'https://www.youtube.com/channel/UCPAA3UOoho0ZDsXI8BWYrYw'
  Slides: 'https://speakerdeck.com/devblackops'

# Default layouts
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  -
    scope:
      path: ''
      type: 'projects'
    values:
      layout: 'project-summary'
  -
    scope:
      path: ''
      type: 'training'
    values:
      layout: 'training-summary'

collections:
  podcasts:
    output: true
  projects:
    output: true
  training:
    output: true

# Build settings
destination: _site
paginate: 5
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
